#!/bin/bash
export VERSION=0.1.1
export DOCKERHUB_USER=nickmaccarthy
export CONTAINER_NAME=devops-runner

BUILD_OPTS='--no-cache'

echo ">>> BUILDING IMAGE $CONTAINER_NAME:$VERSION <<<"
docker build $BUILD_OPTS -t $CONTAINER_NAME:$VERSION . 
echo ">>> TAGGING IMAGE $CONTAINER_NAME:$VERSION <<<"
docker tag $CONTAINER_NAME:$VERSION $DOCKERHUB_USER/$CONTAINER_NAME:$VERSION
echo ">>> PUSHING $CONTAINER_NAME:$VERSION TO DOCKERHUB <<<"
docker push $DOCKERHUB_USER/$CONTAINER_NAME:$VERSION